coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
